coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
